coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
